# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b112a27b77a80ef2fdbd643c92cb1f11dd1190f532d3eaec101d1ac2968f0d1c67b2d44d44d981383c73dbe4922ccd73e4a7b23b1117318686ed95ed97745e86
  stripe_publishable_key: pk_test_pkoY7hC3FITEksAOxxOLCZ8Z
  stripe_secret_key: sk_test_Q8WWPBUpfM3poLpdnY5uwdR5

test:
  secret_key_base: 0816f7c0fd50e387b94b4d8c70473df7cd3b7b74b5eae11bba1097fc388ee8f33db2f82b8eb53485c6d67ebd806b320faa20ff4e34bb4cd8991bec27934bd99f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
